# Remap prefix to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Reload config file
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"

# Split panes using | and -
bind \\ split-window -h
bind - split-window -v
unbind '"'
unbind %

# Enable mouse control
set -g mouse on

set -g @catppuccin_flavor 'mocha'
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

